name: Demo
on: [push]
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World 🌎"

      - name: Checkout code from branch
        uses: actions/checkout@v3

      - name: List files in workspace
        run: |
          ls ${{ github.workspace }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run python
        run: |
          python --version

      - name: Install pytest
        run: |
          pip install pytest

      - name: Run pytest
        run: |
          pytest
