name: Demo
on: [push]
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World 🌎"

      - name: Checkout code from branch
        uses: actions/checkout@v3

      - name: List files in workspace
        run: |
          ls ${{ github.workspace }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: |
          pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install deps
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev --deploy

      - name: Run pytest via pipenv
        run: |
          pipenv run test
